name: Deploy boletas Backend

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build & Publish Backend
        run: |
          dotnet restore
          dotnet publish -c Release -o publish

      - name: Deploy files
        run: |
          sudo systemctl stop boletas-api || true
          sudo rm -rf /var/www/boletas-api/*
          sudo cp -r publish/* /var/www/boletas-api/
          sudo chown -R deploy:deploy /var/www/boletas-api
          sudo systemctl start boletas-api

      - name: Reload nginx
        run: |
          sudo systemctl reload nginx
